// src/components/Projects/Projects.vue
<template>
  <section id="projects" class="section">
    <div class="container">
      <h2 class="section-title text-center" data-aos="fade-up">&lt;PROJECTS /&gt;</h2>

      <h3 class="project-type-title text-center mt-5 mb-4" data-aos="fade-up" data-aos-delay="100">
        TEAM PROJECTS
      </h3>
      <div class="row row-cols-1 row-cols-md-2 g-4 mb-5">
        <div
          class="col"
          v-for="(project, index) in teamProjects"
          :key="project.name"
          data-aos="fade-up"
          :data-aos-delay="200 * (index % 2) + 200"
        >
          <div class="card h-100 shadow-sm project-card">
            <div class="card-body d-flex flex-column">
              <div class="project-title-wrapper">
                <h5 class="card-title fw-bold">{{ project.name }}</h5>
                <p class="project-context text-muted">{{ project.context }} ({{ project.team }})</p>
              </div>
              <p class="card-text text-muted">{{ project.period }}</p>
              <p class="card-text">{{ project.description }}</p>
              <div class="d-flex flex-wrap gap-2 mt-auto pt-3">
                <span
                  v-for="tag in project.tags"
                  :key="tag"
                  class="badge"
                  :style="getTagStyle(tag)"
                >
                  {{ tag }}
                </span>
              </div>
            </div>
            <div class="card-footer bg-white border-0 p-3 d-flex justify-content-end gap-2">
              <a
                v-if="project.githubUrl"
                :href="project.githubUrl"
                target="_blank"
                class="btn btn-dark btn-sm"
                >GitHub</a
              >
              <a
                v-if="project.deployUrl"
                :href="project.deployUrl"
                target="_blank"
                class="btn btn-primary btn-sm"
                >Demo</a
              >
              <button
                v-if="project.readmeUrl"
                @click="openModal(project)"
                class="btn btn-info btn-sm"
              >
                README
              </button>
            </div>
          </div>
        </div>
      </div>

      <h3 class="project-type-title text-center mt-5 mb-4" data-aos="fade-up" data-aos-delay="100">
        PERSONAL PROJECTS
      </h3>
      <div class="row row-cols-1 row-cols-md-2 g-4">
        <div
          class="col"
          v-for="(project, index) in personalProjects"
          :key="project.name"
          data-aos="fade-up"
          :data-aos-delay="200 * (index % 2) + 200"
        >
          <div class="card h-100 shadow-sm project-card">
            <div class="card-body d-flex flex-column">
              <div class="project-title-wrapper">
                <h5 class="card-title fw-bold">{{ project.name }}</h5>
                <p class="project-context text-muted">{{ project.context }}</p>
              </div>
              <p class="card-text text-muted">{{ project.period }}</p>
              <p class="card-text">{{ project.description }}</p>
              <div class="d-flex flex-wrap gap-2 mt-auto pt-3">
                <span
                  v-for="tag in project.tags"
                  :key="tag"
                  class="badge"
                  :style="getTagStyle(tag)"
                >
                  {{ tag }}
                </span>
              </div>
            </div>
            <div class="card-footer bg-white border-0 p-3 d-flex justify-content-end gap-2">
              <a
                v-if="project.githubUrl"
                :href="project.githubUrl"
                target="_blank"
                class="btn btn-dark btn-sm"
                >GitHub</a
              >
              <a
                v-if="project.deployUrl"
                :href="project.deployUrl"
                target="_blank"
                class="btn btn-primary btn-sm"
                >Demo</a
              >
              <button
                v-if="project.readmeUrl"
                @click="openModal(project)"
                class="btn btn-info btn-sm"
              >
                README
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade" id="projectReadmeModal" tabindex="-1">
      <div class="modal-dialog modal-xl modal-dialog-scrollable">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">{{ selectedProject?.name }} - README</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
          </div>
          <div class="modal-body">
            <div v-html="readmeContent" class="readme-content"></div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script src="./Projects.js"></script>
<style scoped src="./Projects.css"></style>

// src/components/Projects/Projects.jsx
import React from 'react';
import './Projects.css';
import { projectsData } from '../../data/projects_data';

const Projects = () => {
  return (
    <div className="projects-content" data-aos="fade-up">
      <header className="mb-4">
        <h2 className="section-title">Projects</h2>
        <div className="title-underline"></div>
      </header>

      <div className="projects-grid-container mt-5">
        <div className="row row-cols-1 row-cols-lg-2 g-4">
          {projectsData &&
            projectsData.map((project, index) => (
              <div key={index} className="col">
                <div className="project-item-card h-100 shadow-sm">
                  <div className="project-card-header d-flex justify-content-between align-items-start mb-3">
                    <span className={`project-badge ${project.type.toLowerCase()}`}>
                      {project.type}
                    </span>
                    <span className="project-period-text">{project.period}</span>
                  </div>

                  <div className="project-info mb-4">
                    <h3 className="project-item-title mb-1">{project.name}</h3>
                    <p className="project-context-text text-secondary mb-3">
                      <span className="context-icon">📌</span> {project.context}
                    </p>
                    <p className="project-desc-text text-muted">{project.description}</p>
                  </div>

                  <div className="project-footer mt-auto">
                    <div className="project-tag-list d-flex flex-wrap gap-2 mb-4">
                      {project.tags &&
                        project.tags.map((tag, tIndex) => (
                          <span key={tIndex} className="tech-tag">
                            {tag}
                          </span>
                        ))}
                    </div>

                    {project.githubUrl && (
                      <a
                        href={project.githubUrl}
                        target="_blank"
                        rel="noreferrer"
                        className="github-link-btn"
                      >
                        <img src="/assets/image/git-icon.png" alt="git" className="btn-icon" />
                        GitHub Repository
                      </a>
                    )}
                  </div>
                </div>
              </div>
            ))}
        </div>
      </div>
    </div>
  );
};

export default Projects;
